### ISSUE TITLE
Dead Link to HartK bed images

### ISSUE THREAD

**Issue by jktightwad** [AndrewEllis93/Ellis-PIF-Profile#13]
The Link to HartKs bed images etc leads to a dead page.  Link is pointing to https://github.com/hartk1213/MISC/tree/main/Voron%20Mods/SuperSlicer but it should be https://github.com/VoronDesign/Voron-Extras/tree/main/Bed_Models

**Comment by AndrewEllis93** [comment]
Fixed in 5a674ca505acd70e9154ffb9928868d2bdcec866. Thanks for bringing this to my attention!
