### ISSUE TITLE
Importing PIF Profile (45 degree) in 2.4.58.2 Has Wall Thickness Bug

### ISSUE THREAD

**Issue by adawalli** [AndrewEllis93/Ellis-PIF-Profile#7]
Hey there - was just checking out your latest PIF profile, and I see the following issue when importing your latest PIF profile for 45 degree. This parameter in particular (`s_wall_thickness`) doesn't actually appear to be in your .ini file (which might be why SS is being so weird)
![2022-04-13_07-46-48](https://user-images.githubusercontent.com/14079121/163240186-3b1dc3d1-ecdd-4096-87ac-93094720eae2.png)

**Comment by AndrewEllis93** [comment]
I think this is just a bug in SS. If I change tabs back and forth, the value keeps hopping around. Tried saving it as 0, and tried adding it to the .ini file as 0 (which is supposed to be the default), but no difference.

**Comment by adawalli** [comment]
ok - will report on SS issues - thanks

**Comment by adawalli** [comment]
Closing as this isn't really a profile issue - however, you may want to warn your users @AndrewEllis93 in the Readme...I have no idea what these random values will do to prints (at one point, it picked 36856 as a value)

**Comment by supermerill** [comment]
It's a quick setting I added for the simple mode, still a bit work in progress.
just forgot to convert the mode from "expert" to "Expert", so it's currently starting with no mode, hence why you're seeing too many fields. Click on "expert" and you should see it disappear.
