### ISSUE TITLE
Failed processing on exporting gcode

### ISSUE THREAD

**Issue by djvj1** [AndrewEllis93/Ellis-PIF-Profile#9]
Loaded your profile (standard and 45) and get this same error on both when exporting gcode:

SuperSlicer has encountered an error:
Failed processing of the output_filename_format template.
Calling ConfigOption::getInt on a non-int ConfigOption

Using your preferred SS version, which is latest anyways.

**Comment by AndrewEllis93** [comment]
I've had this before and I think reopening SS solved it. Of not, you can just set the output name format back to default
